
services:
  db:
    image: postgres:16
    container_name: zenlot-db
    restart: always
    environment:
      POSTGRES_PASSWORD: zenlot
      POSTGRES_USER: zenlot
      POSTGRES_DB: zenlot
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    command: [ "redis-server", "--appendonly", "yes" ]
    container_name: zenlot-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  db-data:
  redis-data: