const CURRENCY_SYMBOL_OVERRIDES: Record<string, string> = {
  aed: 'AED',
  afn: '؋',
  all: 'ALL',
  amd: '֏',
  ang: 'ANG',
  aoa: 'Kz',
  ars: '$',
  aud: '$',
  awg: 'AWG',
  azn: '₼',
  bam: 'KM',
  bbd: '$',
  bdt: '৳',
  bgn: 'BGN',
  bhd: 'BHD',
  bif: 'BIF',
  bmd: '$',
  bnd: '$',
  bob: 'Bs',
  bov: 'BOV',
  brl: 'R$',
  bsd: '$',
  btn: 'BTN',
  bwp: 'P',
  byn: 'BYN',
  bzd: '$',
  cad: '$',
  cdf: 'CDF',
  che: 'CHE',
  chf: 'CHF',
  chw: 'CHW',
  clf: 'CLF',
  clp: '$',
  cny: '¥',
  cop: '$',
  cou: 'COU',
  crc: '₡',
  cuc: '$',
  cup: '$',
  cve: 'CVE',
  czk: 'Kč',
  djf: 'DJF',
  dkk: 'kr',
  dop: '$',
  dzd: 'DZD',
  egp: 'E£',
  ern: 'ERN',
  etb: 'ETB',
  eur: '€',
  fjd: '$',
  fkp: '£',
  gbp: '£',
  gel: '₾',
  ghs: 'GH₵',
  gip: '£',
  gmd: 'GMD',
  gnf: 'FG',
  gtq: 'Q',
  gyd: '$',
  hkd: '$',
  hnl: 'L',
  htg: 'HTG',
  huf: 'Ft',
  idr: 'Rp',
  ils: '₪',
  inr: '₹',
  iqd: 'IQD',
  irr: 'IRR',
  isk: 'kr',
  jmd: '$',
  jod: 'JOD',
  jpy: '¥',
  kes: 'KES',
  kgs: '⃀',
  khr: '៛',
  kmf: 'CF',
  kpw: '₩',
  krw: '₩',
  kwd: 'KWD',
  kyd: '$',
  kzt: '₸',
  lak: '₭',
  lbp: 'L£',
  lkr: 'Rs',
  lrd: '$',
  lsl: 'LSL',
  lyd: 'LYD',
  mad: 'MAD',
  mdl: 'MDL',
  mga: 'Ar',
  mkd: 'MKD',
  mmk: 'K',
  mnt: '₮',
  mop: 'MOP',
  mru: 'MRU',
  mur: 'Rs',
  mvr: 'MVR',
  mwk: 'MWK',
  mxn: '$',
  mxv: 'MXV',
  myr: 'RM',
  mzn: 'MZN',
  nad: '$',
  ngn: '₦',
  nio: 'C$',
  nok: 'kr',
  npr: 'Rs',
  nzd: '$',
  omr: 'OMR',
  pab: 'PAB',
  pen: 'PEN',
  pgk: 'PGK',
  php: '₱',
  pkr: 'Rs',
  pln: 'zł',
  pyg: '₲',
  qar: 'QAR',
  ron: 'lei',
  rsd: 'RSD',
  rub: '₽',
  rwf: 'RF',
  sar: 'SAR',
  sbd: '$',
  scr: 'SCR',
  sdg: 'SDG',
  sek: 'kr',
  sgd: '$',
  shp: '£',
  sle: 'SLE',
  sll: 'SLL',
  sos: 'SOS',
  srd: '$',
  ssp: '£',
  stn: 'Db',
  svc: 'SVC',
  syp: '£',
  szl: 'SZL',
  thb: '฿',
  tjs: 'TJS',
  tmt: 'TMT',
  tnd: 'TND',
  top: 'T$',
  try: '₺',
  ttd: '$',
  twd: '$',
  tzs: 'TZS',
  uah: '₴',
  ugx: 'UGX',
  usd: '$',
  usn: 'USN',
  uyi: 'UYI',
  uyu: '$',
  uzs: 'UZS',
  ved: 'VED',
  ves: 'VES',
  vnd: '₫',
  vuv: 'VUV',
  wst: 'WST',
  xaf: 'FCFA',
  xag: 'XAG',
  xau: 'XAU',
  xba: 'XBA',
  xbb: 'XBB',
  xbc: 'XBC',
  xbd: 'XBD',
  xcd: '$',
  xdr: 'XDR',
  xof: 'F CFA',
  xpd: 'XPD',
  xpf: 'CFPF',
  xpt: 'XPT',
  xsu: 'XSU',
  xts: 'XTS',
  xua: 'XUA',
  xxx: '¤',
  yer: 'YER',
  zar: 'R',
  zmw: 'ZK',
  zwg: 'ZWG',
};

export function getCurrencySymbol(currency?: string | null): string {
  const code = currency?.trim() || 'usd';
  const normalizedCode = code.toLowerCase();

  if (CURRENCY_SYMBOL_OVERRIDES[normalizedCode]) {
    return CURRENCY_SYMBOL_OVERRIDES[normalizedCode];
  }

  try {
    const symbol = new Intl.NumberFormat('en-US', {
      style: 'currency',
      currency: normalizedCode,
      currencyDisplay: 'narrowSymbol',
      minimumFractionDigits: 0,
      maximumFractionDigits: 0,
    })
      .formatToParts(0)
      .find((part) => part.type === 'currency')?.value;

    return symbol || code;
  } catch {
    return code;
  }
}
